default: &default
  adapter: postgresql
  encoding: unicode
  username: pepe
  password: pepe  # Reemplaza 'contraseña' con la contraseña que has configurado para el usuario 'pepe'
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: y_development
